export const ADD_TO_CART = 'ADD_TO_CART';
export const DECREMENT_ITEM  = 'DECREMENT_ITEM'
export const INCREMENT_ITEM  = 'INCREMENT_ITEM'
export const CLEAR_CART  = 'CLEAR_CART'
export const REMOVE_ITEM  = 'REMOVE_ITEM'
export const SET_LAST_VISITED_VENDOR  = 'SET_LAST_VISITED_VENDOR'
